// Renders the link preview image and the icons into docs/public:
//   og.svg (1200x630, text outlined to paths so it renders the same everywhere) and og.png,
//   apple-touch-icon.png (180x180) and favicon.ico (32x32), both from logo.svg.
// Text uses Noto Sans CJK SC (its Latin glyphs are Source Sans), loaded from the system fonts.
// Usage: npm run og --workspace loader-kit-docs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const publicDir = (file: string) => fileURLToPath(new URL(`../public/${file}`, import.meta.url));
const FONT = 'Noto Sans CJK SC';

function dots(cx: number, cy: number, radius: number, size: number): string {
  return Array.from({ length: 8 }, (_, i) => {
    const angle = -Math.PI / 2 - (i * Math.PI) / 4;
    const k = i / 7;
    const x = (cx + radius * Math.cos(angle)).toFixed(2);
    const y = (cy + radius * Math.sin(angle)).toFixed(2);
    const r = (size * (1 - 0.42 * k)).toFixed(2);
    return `<circle cx="${x}" cy="${y}" r="${r}" fill="url(#brand)" fill-opacity="${(1 - 0.62 * k).toFixed(2)}"/>`;
  }).join('');
}

function bars(x: number, y: number): string {
  const heights = [0.45, 0.8, 1, 0.65, 0.35];
  return heights
    .map((h, i) => {
      const height = 64 * h;
      return `<rect x="${x + i * 20}" y="${(y - height / 2).toFixed(1)}" width="12" height="${height.toFixed(1)}" rx="6" fill="#22d3ee" fill-opacity="${(0.5 + h / 2).toFixed(2)}"/>`;
    })
    .join('');
}

const source = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
<defs>
<radialGradient id="glow" cx="0.2" cy="0.5" r="0.62"><stop offset="0" stop-color="#7c3aed" stop-opacity="0.42"/><stop offset="0.55" stop-color="#06b6d4" stop-opacity="0.08"/><stop offset="1" stop-color="#06b6d4" stop-opacity="0"/></radialGradient>
<linearGradient id="brand" x1="110" y1="140" x2="410" y2="460" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#a78bfa"/><stop offset="1" stop-color="#22d3ee"/></linearGradient>
<linearGradient id="title" x1="0" y1="0" x2="460" y2="0" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#c4b5fd"/><stop offset="1" stop-color="#67e8f9"/></linearGradient>
</defs>
<rect width="1200" height="630" fill="#0f0d17"/>
<rect width="1200" height="630" fill="url(#glow)"/>
<g>${dots(260, 315, 140, 32)}</g>
<g transform="translate(500 0)">
<text x="0" y="250" font-family="${FONT}" font-weight="700" font-size="104" fill="url(#title)" letter-spacing="-2">LoaderKit</text>
<text x="2" y="322" font-family="${FONT}" font-weight="500" font-size="31" fill="#ece9f6">One JSON spec, native loaders everywhere.</text>
<text x="2" y="378" font-family="${FONT}" font-weight="400" font-size="28" fill="#a9a3bd">Android, iOS, macOS, Windows and the web</text>
${bars(2, 470)}
<text x="124" y="480" font-family="${FONT}" font-weight="500" font-size="24" fill="#a9a3bd">maitrungduc1410.github.io/loader-kit</text>
</g>
</svg>
`;

const fonts = { font: { loadSystemFonts: true, defaultFontFamily: FONT } };

// usvg's output has the text converted to paths, so og.svg no longer needs the font.
const outlined = new Resvg(source, fonts).toString();
const comment = `<!--
  Link preview image for the docs site (Open Graph and Twitter), 1200x630. Generated by
  docs/scripts/og.ts, which also renders og.png; text is outlined to paths.
  Text: "LoaderKit", "One JSON spec, native loaders everywhere.",
  "Android, iOS, macOS, Windows and the web", "maitrungduc1410.github.io/loader-kit".
-->
`;
const og = outlined.replace(/^(<svg[^>]*>)/, `$1\n${comment}`);
writeFileSync(publicDir('og.svg'), og);
writeFileSync(publicDir('og.png'), new Resvg(og, { fitTo: { mode: 'width', value: 1200 } }).render().asPng());

const logo = readFileSync(publicDir('logo.svg'), 'utf8');
const inner = logo.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>[^<]*<\/title>/, '');

// iOS masks the icon itself and shows black behind transparent pixels, so the touch icon is opaque.
const touch = `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 64 64">
<rect width="64" height="64" fill="#0f0d17"/>
<g transform="translate(9.6 9.6) scale(0.7)">${inner}</g>
</svg>`;
writeFileSync(publicDir('apple-touch-icon.png'), new Resvg(touch, { fitTo: { mode: 'width', value: 180 } }).render().asPng());

/** An .ico file that holds one PNG image, which every current browser reads. */
function ico(png: Buffer, size: number): Buffer {
  const header = Buffer.alloc(22);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(1, 4);
  header.writeUInt8(size, 6);
  header.writeUInt8(size, 7);
  header.writeUInt8(0, 8);
  header.writeUInt8(0, 9);
  header.writeUInt16LE(1, 10);
  header.writeUInt16LE(32, 12);
  header.writeUInt32LE(png.length, 14);
  header.writeUInt32LE(22, 18);
  return Buffer.concat([header, png]);
}
const favicon = new Resvg(logo, { fitTo: { mode: 'width', value: 32 } }).render().asPng();
writeFileSync(publicDir('favicon.ico'), ico(favicon, 32));

console.log('Wrote og.svg, og.png, apple-touch-icon.png and favicon.ico to docs/public');
