// Apart from the specs, so the lite entry lists the names without loading every indicator.
const NAMES = [
  'Atom',
  'AudioEqualizer',
  'BallBeat',
  'BallClipRotate',
  'BallClipRotateMultiple',
  'BallClipRotatePulse',
  'BallDoubleBounce',
  'BallFall',
  'BallGridBeat',
  'BallGridPulse',
  'BallHelix',
  'BallHoneycomb',
  'BallMerge',
  'BallPulse',
  'BallPulseRise',
  'BallPulseSync',
  'BallRotate',
  'BallRotateChase',
  'BallScale',
  'BallScaleMultiple',
  'BallScaleRipple',
  'BallScaleRippleMultiple',
  'BallSpinFadeLoader',
  'BallSquareSpin',
  'BallTrianglePath',
  'BallZigZag',
  'BallZigZagDeflect',
  'ChasingDots',
  'CircleStrokeSpin',
  'CubeTransition',
  'JellyBox',
  'LineScale',
  'LineScaleParty',
  'LineScalePulseOut',
  'LineScalePulseOutRapid',
  'LineSlide',
  'LineSpinFadeLoader',
  'NewtonCradle',
  'Orbit',
  'Pacman',
  'Radar',
  'RunningDots',
  'SemiCircleSpin',
  'SquareGridFlip',
  'SquareGridWave',
  'SquareSpin',
  'Timer',
  'TriangleOrbit',
  'TriangleSkewSpin',
  'TripleArcSpin',
] as const;

export type BuiltinIndicatorName = (typeof NAMES)[number];

export const BUILTIN_INDICATOR_NAMES: BuiltinIndicatorName[] = [...NAMES];
