// Generates everything the platform engines share with this package:
//   - test-vectors/*.json: expected element states that every engine must reproduce
//   - the built-in specs as JSON strings for Kotlin, Swift and C#
//   - spec/schema.json: the JSON Schema of a spec, for editors and tools
// Usage: node spec/scripts/generate.ts [--check]
// With --check nothing is written; the script fails when a generated file is out of date.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  BUILTIN_INDICATORS,
  BUILTIN_INDICATOR_NAMES,
  evaluate,
  prepareParts,
  resolveParams,
  timeForCycleProgress,
  type IndicatorSpec,
  type Params,
} from '../src/index.ts';
import { EDGE_CASES, type VectorSource } from './edge-cases.ts';
import { indicatorSpecSchema } from './schema.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const check = process.argv.includes('--check');
const stale: string[] = [];

function emit(path: string, content: string) {
  const file = join(root, path);
  if (check) {
    if (!existsSync(file) || readFileSync(file, 'utf8') !== content) stale.push(path);
    return;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
}

const HEADER = 'Generated by spec/scripts/generate.ts. Do not edit.';

// ----- test vectors -----

function sampleTimes(spec: IndicatorSpec, params: Params): number[] {
  const parts = prepareParts(spec, resolveParams(spec, params));
  const offsets = parts.flatMap((part) => part.offsets);
  const durations = parts.flatMap((part) => [part.duration, ...part.durations]);
  const end = Math.max(0, ...offsets) + 2 * Math.max(...durations);
  const times = new Set<number>();
  const steps = 40;
  for (let i = 0; i <= steps; i++) times.add(round((end * i) / steps));
  // Exact keyframe boundaries of the first element of each part and of its group tracks, where
  // off-by-one segment bugs show up.
  for (const part of parts) {
    const offset = part.offsets[0] ?? 0;
    const duration = part.durations[0] ?? part.duration;
    for (const track of part.part.tracks ?? []) {
      for (const keyTime of track.keyTimes) {
        for (const start of [offset, offset + duration]) {
          const t = round(start + keyTime * duration);
          if (t >= 0) times.add(t);
        }
      }
    }
    for (const track of part.part.groupTracks ?? []) {
      for (const keyTime of track.keyTimes) times.add(round((1 + keyTime) * part.duration));
    }
  }
  return [...times].sort((a, b) => a - b);
}

const round = (value: number) => Math.round(value * 1e9) / 1e9;

function vector({ id, description, spec, params = {} }: VectorSource) {
  return {
    id,
    description,
    spec,
    params,
    shapes: prepareParts(spec, resolveParams(spec, params)).map((part) => part.shape),
    samples: sampleTimes(spec, params).map((t) => ({ t, elements: evaluate(spec, t, params) })),
    cycleProgress: [0, 0.25, 0.5, 0.75, 1].map((cycleProgress) => ({
      cycleProgress,
      t: timeForCycleProgress(spec, cycleProgress, params),
    })),
  };
}

const sources: VectorSource[] = [
  ...BUILTIN_INDICATOR_NAMES.map((name) => ({
    id: name,
    description: `Built-in ${name} with default params`,
    spec: BUILTIN_INDICATORS[name],
  })),
  {
    id: 'BallPulse-params',
    description: 'BallPulse with count and minScale overridden, plus an unknown param that must be ignored',
    spec: BUILTIN_INDICATORS.BallPulse,
    params: { count: 5, minScale: 0.5, unknown: 42 },
  },
  ...EDGE_CASES,
];

const vectors = sources.map(vector);
// One element state per line keeps the files small and the diffs readable.
function vectorJson({ samples, ...rest }: ReturnType<typeof vector>): string {
  const head = JSON.stringify(rest, null, 2).slice(0, -2);
  const body = samples
    .map(({ t, elements }) => `    {"t": ${t}, "elements": [\n${elements.map((e) => `      ${JSON.stringify(e)}`).join(',\n')}\n    ]}`)
    .join(',\n');
  return `${head},\n  "samples": [\n${body}\n  ]\n}\n`;
}

for (const item of vectors) {
  emit(`test-vectors/${item.id}.json`, vectorJson(item));
}
emit(
  'test-vectors/index.json',
  `${JSON.stringify({ note: HEADER, tolerance: 1e-6, files: vectors.map((item) => `${item.id}.json`) }, null, 2)}\n`
);

// The engine tests expect index.json to list every file of test-vectors/, so leftovers must go.
const vectorFiles = new Set(['index.json', ...vectors.map((item) => `${item.id}.json`)]);
for (const name of readdirSync(join(root, 'test-vectors'))) {
  if (!name.endsWith('.json') || vectorFiles.has(name)) continue;
  if (check) stale.push(`test-vectors/${name}`);
  else rmSync(join(root, 'test-vectors', name));
}

// ----- built-in specs for the native engines -----

const builtins = BUILTIN_INDICATOR_NAMES.map((name) => ({
  name,
  json: JSON.stringify(BUILTIN_INDICATORS[name]),
}));

const kotlinString = (json: string) => JSON.stringify(json).replace(/\$/g, '\\$');
emit(
  'android/loaderkit-core/src/main/kotlin/io/github/maitrungduc1410/loaderkit/BuiltinIndicatorSpecs.kt',
  `// ${HEADER}
package io.github.maitrungduc1410.loaderkit

internal object BuiltinIndicatorSpecs {
    val names: List<String> = listOf(${builtins.map(({ name }) => `"${name}"`).join(', ')})

    val json: Map<String, String> = mapOf(
${builtins.map(({ name, json }) => `        "${name}" to ${kotlinString(json)},`).join('\n')}
    )
}
`
);

emit(
  'apple/Sources/LoaderKitCore/BuiltinIndicatorSpecs.swift',
  `// ${HEADER}

enum BuiltinIndicatorSpecs {
    static let names: [String] = [${builtins.map(({ name }) => `"${name}"`).join(', ')}]

    static let json: [String: String] = [
${builtins.map(({ name, json }) => `        "${name}": #"${json}"#,`).join('\n')}
    ]
}
`
);

emit(
  'windows/LoaderKit.Core/BuiltinIndicatorSpecs.cs',
  `// ${HEADER}
using System.Collections.Generic;

namespace LoaderKit
{
    internal static class BuiltinIndicatorSpecs
    {
        public static readonly IReadOnlyList<string> Names = new[] { ${builtins.map(({ name }) => `"${name}"`).join(', ')} };

        public static readonly IReadOnlyDictionary<string, string> Json = new Dictionary<string, string>
        {
${builtins.map(({ name, json }) => `            ["${name}"] = @"${json.replace(/"/g, '""')}",`).join('\n')}
        };
    }
}
`
);

emit('spec/schema.json', `${JSON.stringify(indicatorSpecSchema(), null, 2)}\n`);

if (check) {
  if (stale.length > 0) {
    console.error(`Out of date, run \`npm run generate\`:\n${stale.map((path) => `  ${path}`).join('\n')}`);
    process.exit(1);
  }
  console.log('Generated files are up to date.');
} else {
  console.log(`Wrote ${vectors.length} test vectors and ${builtins.length} built-in specs under ${relative(process.cwd(), root) || '.'}`);
}
